#!/usr/bin/env python3
"""Derive a weight-free native linear template from ~/ane's verified primitives."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys

cli=argparse.ArgumentParser(description=__doc__)
cli.add_argument('--ane-root',type=Path,default=Path.home()/'ane')
args=cli.parse_args()
sys.path.insert(0,str(args.ane_root/'gpt2'))
from hwx import parse_container,parse_tasks,relocate
arrays=[];sources=[]
for k,n in [(768,768),(768,3072),(3072,768)]:
 path=args.ane_root/f'gpt2/training/orion/kernels/linear_32_{k}_{n}_forward/hwx/model.hwx'
 data=path.read_bytes();c=parse_container(data)
 assert not any(s['name'].startswith('__KERN') for s in c['segments']), 'learned coefficients are forbidden in templates'
 text=next(s for s in c['segments'] if s['name']=='__TEXT')
 const=next(s for s in c['sections'] if s['name']=='__const' and s['segment']=='__TEXT')
 assert not any(data[const['offset']:const['offset']+const['size']]), 'expected zero bias constants'
 raw=data[text['fileoff']:text['fileoff']+text['filesize']]
 tasks=parse_tasks(raw,c['thread']['td_size'],c['thread']['td_count'])
 program=relocate(raw,tasks,{0:0,1:2,3:3,4:4,5:5,6:6,7:7})
 arrays.append(struct.unpack('<576I',program[:2304]))
 sources.append({'primitive':f'linear_32_{k}_{n}_forward','hwx_sha256':hashlib.sha256(data).hexdigest()})
base=arrays[0]
output='// Generated by tools/make_ane_template.py. Register instructions only; no learned weights.\n'
output+='static const uint32_t ane_linear_template[576] = {\n'
output+='\n'.join('    '+', '.join(f'0x{x:08x}' for x in base[i:i+8])+',' for i in range(0,len(base),8))+'\n};\n'
output+='typedef struct { unsigned offset, scale; } AneDimensionPatch;\n'
for axis,variant in [('n',arrays[1]),('k',arrays[2])]:
 patches=[]
 for i,(a,b) in enumerate(zip(base,variant)):
  if a==b or i*4 in [4,0x204,0x704,0x37c,0x384,0x388]:continue
  scale=(b-a)//2304
  assert scale*2304==b-a
  patches.append((i*4,scale))
 output+=f'static const AneDimensionPatch ane_{axis}_patches[] = {{\n'
 output+='\n'.join(f'    {{0x{off:x}, {scale}}},' for off,scale in patches)+'\n};\n'
Path('ane/linear_template.h').write_text(output)
Path('ane/template-provenance.json').write_text(json.dumps({'architecture':'H13G/T8103','reference':'~/ane/gpt2/training/orion/kernels','sources':sources,'template_sha256':hashlib.sha256(output.encode()).hexdigest(),'learned_weights_in_template':False},indent=2)+'\n')
